--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PMVirion/InjectorUtils
build-by-default: true
branches:
- main
projects:
  InjectorUtils:
    path: ""
    model: virion
    type: library
...
